# Generated by Django 2.1.1 on 2020-07-17 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
