# Generated by Django 2.1.1 on 2020-07-17 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegiado', '0001_initial'),
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentencia',
            fields=[
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proceso.Proceso')),
                ('nombre', models.TextField(default='SENTENCIA DEL PROCESO')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('docfile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
                ('ponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colegiado.Colegiado')),
            ],
        ),
    ]
