# Generated by Django 2.1.1 on 2020-07-17 20:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegiado', '0001_initial'),
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='proceso.Proceso')),
                ('nombre', models.TextField(default='ACTA DE SESIÓN DE FALLO')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('consta', models.TextField(blank=True, max_length=500, null=True)),
                ('docfile', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Canon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcanon', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Veto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='canon',
            field=models.ManyToManyField(blank=True, to='acta.Canon'),
        ),
        migrations.AddField(
            model_name='acta',
            name='defensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person10', to='colegiado.Colegiado'),
        ),
        migrations.AddField(
            model_name='acta',
            name='juez1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person11', to='colegiado.Colegiado'),
        ),
        migrations.AddField(
            model_name='acta',
            name='juez2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person12', to='colegiado.Colegiado'),
        ),
        migrations.AddField(
            model_name='acta',
            name='ponente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person13', to='colegiado.Colegiado'),
        ),
        migrations.AddField(
            model_name='acta',
            name='presidente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person9', to='colegiado.Colegiado'),
        ),
        migrations.AddField(
            model_name='acta',
            name='veto',
            field=models.ManyToManyField(blank=True, to='acta.Veto'),
        ),
    ]
